# 数値解析2020 レポート

**VIII-A.** 
(1) $m$ 個 $(m>2)$ のデータ点 $(x_i, y_i)$ $(1\le i\le m)$ に対し最小2乗法を用いて多項式 $p_1(x)=a_0 + a_1 x$ を当てはめる場合の正規方程式を導出せよ。また求めた正規方程式は

\begin{equation*}
    X \equiv \begin{bmatrix}
    1 & x_1\\
    1 & x_2\\
    \vdots & \vdots\\
    1 & x_m\\
    \end{bmatrix}, \mathbf{a}\equiv \begin{bmatrix}
        a_0\\a_1
    \end{bmatrix}, 
    \mathbf{y}\equiv \begin{bmatrix}
        y_0\\y_1\\ \vdots \\y_m
        \end{bmatrix}
\end{equation*}

を用いて $(X^\mathsf{T}X) \mathbf{a} = X^\mathsf{T} \mathbf{y}$と表せる事を示せ

(2) 問1で求めた正規方程式を $\mathbf{a}$ について解く事で $a_0$ を $s_x^2$, $s_{xy}$ を用いて、$a_1$ を $a_0, \bar{x},\bar{y}$ を用いて表せ。
ここで $s_x^2$ は $x_i$ の分散、$s_{xy}$ は $x_i$ と $y_i$ の共分散、 $\bar{x}$ は $x_i$ の平均値、$\bar{y}$ は $y_i$ の平均値を表す。

(3) 問2で求めた式を用いて以下の表にある8つのデータ点 $(0.0, 10.0)$, $(1.0, 21.0)$, $(3.00, 66.0)$, $(4.00, 97.0)$, $(5.00, 118)$ の残差の2乗和を最小化する $p_1(x)$ を求めよ。

$\mathbf{x} = [0, 1, 1, 2, 2, 3, 5, 6]$

$\mathbf{y} = [10, 21, 23, 49, 52, 65,  95, 121]$


#

**VIII-B.** (1) VIII-A の問3にある8つのデータ点を最小2乗法を用いて3次多項式 $p_3(x)$ を当てはめる問題を考える。正規方程式をLU分解で解くプログラムを作成し $p_3(x)$ の係数を有効数字4桁で5桁目を四捨五入して求めよ。
作成したプログラムも提出すること。プログラミング言語は問わない。

(2) 問1の正規方程式をハウスホルダー法を用いてQR分解してから解くプログラムを作成し $p_3(x)$ の係数を有効数字4桁で5桁目を四捨五入して求めよ。
作成したプログラムも提出すること。プログラミング言語は問わない。

以下Python3を用いたプログラム例を示す。

In [ ]:
# Pythonのバージョン確認
import sys
print(sys.version)

3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]


# 解答コード LU分解

In [ ]:
import numpy as np

a = np.array([0, 1, 1, 2, 2, 3, 5, 6])
b = np.array([1, 2, 3, 15, 15, 33,  75, 146])

m = len(a)

#XT =np.array([np.ones(m), a])
#XT =np.array([np.ones(m), a, a**2])
XT =np.array([np.ones(m), a, a**2, a**3])

b = np.dot(XT, b)

n = len(XT)

print("m", m, "n", n)

print(XT)

A = np.dot(XT, np.transpose(XT))
L = np.identity(n, dtype=float)
M = np.zeros((n, n))
y = np.zeros(n)


# LU factorization
for k in range(n-1): # 0, 1, ..., n-2
    for i in range(k+1, n): # k+1, k+2, ... , n-1
        M[i][k] = A[i][k]/A[k][k]
        A[i][k] = 0
        for j in range(k+1, n): # k+1, k+2, ..., n-1
            A[i][j] = A[i][j] - M[i][k]*A[k][j]
        L[i][k] = M[i][k]

print("A")
print(A)
print("L")
print(L)

# Forward substitution

y[0] = b[0]
for i in range(1, n): # 1, 2, ..., n-1
    sum = 0
    for j in range(i): # 0, ... , i-1
        sum += L[i][j]*y[j] 
    y[i] = b[i] - sum

print("y")
print(y)

z = np.zeros(n)

# Backward substitution
z[n-1] = y[n-1] / A[n-1][n-1]
for i in range(n-2, -1, -1): # n-2, n-1, ..., 0
    sum = 0
    for j in range(i+1,n): # i+1, i+2, ..., n-1
        sum += A[i][j]*z[j]
    z[i] = (y[i] - sum) / A[i][i]

print(z)

#print("p(x) = {0:e} + {1:e} * x".format(z[0], z[1]))
#print("p(x) = {0:e} + {1:e} * x + {2:e} * x**2".format(z[0], z[1], z[2]))
print("p(x) = {0:e} + {1:e} * x + {2:e} * x**2 + {3:e} * x**3".format(z[0], z[1], z[2], z[3]))

m 8 n 4
[[  1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.   1.   2.   2.   3.   5.   6.]
 [  0.   1.   1.   4.   4.   9.  25.  36.]
 [  0.   1.   1.   8.   8.  27. 125. 216.]]
A
[[   8.           20.           80.          386.        ]
 [   0.           30.          186.         1071.        ]
 [   0.            0.           82.8         709.8       ]
 [   0.            0.            0.          196.06521739]]
L
[[ 1.          0.          0.          0.        ]
 [ 2.5         1.          0.          0.        ]
 [10.          6.2         1.          0.        ]
 [48.25       35.7         8.57246377  1.        ]]
y
[290.         690.         375.         206.82608696]
[-2.82658831 13.32725358 -4.51397051  1.05488413]
p(x) = -2.826588e+00 + 1.332725e+01 * x + -4.513971e+00 * x**2 + 1.054884e+00 * x**3


In [ ]:
y = np.array([1, 2, 3, 15, 15, 33,  75, 146])
np.sum((y - (z[0] + z[1]*a + z[2]*a**2 + z[3]*a**3))**2)

194.9528772591196

# 解答コード QR分解

In [ ]:
import numpy as np

#x = np.array([0, 1, 2, 3, 4, 5])
x = np.array([0, 1, 1, 2, 2, 3, 5, 6])
#y = np.array([10, 25, 51, 66, 97, 118])
y = np.array([1, 2, 3, 15, 15, 33,  75, 146])

m = len(x)

XT =np.array([np.ones(m), x, x**2, x**3])
n = len(XT)
print("m", m, "n", n)
print(XT)
print(np.dot(XT, np.transpose(XT)))

m 8 n 4
[[  1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.   1.   2.   2.   3.   5.   6.]
 [  0.   1.   1.   4.   4.   9.  25.  36.]
 [  0.   1.   1.   8.   8.  27. 125. 216.]]
[[8.000e+00 2.000e+01 8.000e+01 3.860e+02]
 [2.000e+01 8.000e+01 3.860e+02 2.036e+03]
 [8.000e+01 3.860e+02 2.036e+03 1.121e+04]
 [3.860e+02 2.036e+03 1.121e+04 6.314e+04]]


In [ ]:
U = []
for i in range(n):
    a = XT[i][i:]
    norm_a = np.linalg.norm(a)
    d = np.sign(a[0]) * norm_a
    w = - d * np.append([1], np.zeros(m-1-i))
    u = (a - w) / (np.sqrt(norm_a*(norm_a + abs(a[0]))))
    U.append(np.append(np.zeros(i), u))

    XT[i][i:] = w

    for j in range(i+1, n):
        XT[j][i:] = XT[j][i:] - np.dot(u, XT[j][i:])*u

print(XT)

[[  -2.82842712   -0.           -0.           -0.           -0.
    -0.           -0.           -0.        ]
 [  -7.07106781    5.47722558    0.            0.            0.
     0.            0.            0.        ]
 [ -28.28427125   33.95879857    9.09945053    0.            0.
     0.            0.            0.        ]
 [-136.47160877  195.53695303   78.00471     -14.002329     -0.
    -0.           -0.           -0.        ]]


In [ ]:
H = np.eye(m)
for i in range(n):
    H = np.array(np.eye(m) - np.outer(U[i], U[i])) @ H
y = H[:n] @ y
print(y)

[-102.53048327  125.97618823   41.21127959  -14.77083469]


In [ ]:
X =  np.transpose(XT)
R = X[:n]
print(R)

alpha = np.zeros(n)

# Backward substitution
alpha[n-1] = y[n-1] / R[n-1][n-1]
for i in range(n-2, -1, -1): # n-2, n-1, ..., 0
    sum = 0
    for j in range(i+1,n): # i+1, i+2, ..., n-1
        sum += R[i][j]*alpha[j]
    alpha[i] = (y[i] - sum) / R[i][i]

print(alpha)
print("p(x) = {0:e} + {1:e} * x + {2:e} * x**2 + {3:e} * x**3".format(alpha[0], alpha[1], alpha[2], alpha[3]))

[[  -2.82842712   -7.07106781  -28.28427125 -136.47160877]
 [  -0.            5.47722558   33.95879857  195.53695303]
 [  -0.            0.            9.09945053   78.00471   ]
 [  -0.            0.            0.          -14.002329  ]]
[-2.82658831 13.32725358 -4.51397051  1.05488413]
p(x) = -2.826588e+00 + 1.332725e+01 * x + -4.513971e+00 * x**2 + 1.054884e+00 * x**3


In [ ]:
print(U)
print(H)
print(X)

[array([1.16342313, 0.30389063, 0.30389063, 0.30389063, 0.30389063,
       0.30389063, 0.30389063, 0.30389063]), array([ 0.        , -1.0745411 , -0.14391126,  0.02599772,  0.02599772,
        0.1959067 ,  0.53572467,  0.70563366]), array([ 0.        ,  0.        , -1.05270219, -0.455592  , -0.455592  ,
       -0.59962829, -0.26133143,  0.22100172]), array([ 0.        ,  0.        ,  0.        ,  1.07555497,  0.14580239,
       -0.26598886, -0.33831718,  0.79794397])]
[[-0.35355339 -0.35355339 -0.35355339 -0.35355339 -0.35355339 -0.35355339
  -0.35355339 -0.35355339]
 [-0.45643546 -0.27386128 -0.27386128 -0.09128709 -0.09128709  0.09128709
   0.45643546  0.63900965]
 [ 0.6044321   0.03296902  0.03296902 -0.31870056 -0.31870056 -0.45057666
  -0.05494837  0.47255601]
 [ 0.43910915 -0.26626005 -0.26626005 -0.17569541 -0.17569541  0.28230293
   0.58660014 -0.42410129]
 [ 0.11960357  0.01486852 -0.43026569 -0.32396487  0.81159528 -0.18862148
  -0.02529283  0.02207749]
 [ 0.12732313  0.36500

# ↓ レポート表示用

In [ ]:
import numpy as np

x = np.array([0, 1, 1, 2, 2, 3, 5, 6])
y = np.array([1, 2, 3, 15, 15, 33,  75, 146])

m = len(x)

XT = np.array([np.ones(m), x, x**2, x**3])
X = np.transpose(XT)

n = len(XT)
print("m", m, "n", n)
print(X)
print(np.dot(np.transpose(X), X))

U = np.zeros(m*n).reshape(m, n)

for j in range(n):
    norm_x = 0
    for i in range(j, m):
        norm_x = norm_x + X[i][j]**2
    norm_x = np.sqrt(norm_x)
    if X[j][j] >= 0:
        d = norm_x
    else:
        d = - norm_x
    g = np.sqrt(norm_x*(norm_x + abs(X[j][j])))

    U[j][j] = (X[j][j] + d) / g
    X[j][j] = - d
    for i in range(j+1, m):
        U[i][j] = X[i][j] / g
        X[i][j] = 0

    temp = np.zeros(m*n).reshape(m, n)
    for i in range(j, m):
        for k in range(j+1, n):
            sum = 0
            for l in range(j, m):
                sum = sum + U[l][j] * X[l][k]
            temp[i][k] = X[i][k] - sum * U[i][j]
    for i in range(j, m):
        for k in range(j+1, n):
            X[i][k] = temp[i][k]

print(X)

H = np.zeros(m**2).reshape(m, m)

for i in range(m):
    H[i][i] = 1

temp = np.zeros(m*m).reshape(m, m)
for l in range(n):
    for i in range(m):
        for j in range(m):
            sum = 0
            for k in range(m):
                if i == k:
                    sum = sum + (1 - U[i][l] * U[k][l]) * H[k][j]
                else:
                    sum = sum + ( - U[i][l] * U[k][l]) * H[k][j]
            temp[i][j] = sum
    for i in range(m):
        for j in range(m):
            H[i][j] = temp[i][j]

z = np.zeros(n)

for j in range(n):
    sum = 0
    for k in range(m):
        sum = sum + H[j][k] * y[k]
    z[j] = sum

alpha = np.zeros(n)

# Backward substitution
alpha[n-1] =z[n-1] / X[n-1][n-1]
for i in range(n-2, -1, -1): # n-2, n-1, ..., 0
    sum = 0
    for j in range(i+1,n): # i+1, i+2, ..., n-1
        sum = sum + X[i][j]*alpha[j]
    alpha[i] = (z[i] - sum) / X[i][i]

print(alpha)
print("p(x) = {0:e} + {1:e} * x + {2:e} * x**2 + {3:e} * x**3".format(alpha[0], alpha[1], alpha[2], alpha[3]))

m 8 n 4
[[  1.   0.   0.   0.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   5.  25. 125.]
 [  1.   6.  36. 216.]]
[[8.000e+00 2.000e+01 8.000e+01 3.860e+02]
 [2.000e+01 8.000e+01 3.860e+02 2.036e+03]
 [8.000e+01 3.860e+02 2.036e+03 1.121e+04]
 [3.860e+02 2.036e+03 1.121e+04 6.314e+04]]
[[  -2.82842712   -7.07106781  -28.28427125 -136.47160877]
 [   0.            5.47722558   33.95879857  195.53695303]
 [   0.            0.            9.09945053   78.00471   ]
 [   0.            0.            0.          -14.002329  ]
 [   0.            0.            0.            0.        ]
 [   0.            0.            0.            0.        ]
 [   0.            0.            0.            0.        ]
 [   0.            0.            0.            0.        ]]
[-2.82658831 13.32725358 -4.51397051  1.05488413]
p(x) = -2.826588e+00 + 1.332725e+01 * x + -4.513971e+00 * x**2 + 1.054884e+00 * x**3


In [ ]:
print(np.transpose(H[n:]) @ H[n:])
print(H[n:] @ np.transpose(H[n:]))

[[ 0.10851166 -0.15301031 -0.15301031  0.10311564  0.10311564  0.06504786
  -0.14103559  0.0672654 ]
 [-0.15301031  0.72801863 -0.27198137 -0.18627342 -0.18627342 -0.00997893
   0.15799978 -0.07850094]
 [-0.15301031 -0.27198137  0.72801863 -0.18627342 -0.18627342 -0.00997893
   0.15799978 -0.07850094]
 [ 0.10311564 -0.18627342 -0.18627342  0.73422774 -0.26577226 -0.21066637
   0.00221754  0.00942455]
 [ 0.10311564 -0.18627342 -0.18627342 -0.26577226  0.73422774 -0.21066637
   0.00221754  0.00942455]
 [ 0.06504786 -0.00997893 -0.00997893 -0.21066637 -0.21066637  0.5839524
  -0.35702406  0.14931441]
 [-0.14103559  0.15799978  0.15799978  0.00221754  0.00221754 -0.35702406
   0.31954762 -0.14192261]
 [ 0.0672654  -0.07850094 -0.07850094  0.00942455  0.00942455  0.14931441
  -0.14192261  0.06349558]]
[[ 1.00000000e+00  2.07117905e-16  8.28828359e-17 -1.48571421e-16]
 [ 2.07117905e-16  1.00000000e+00  9.98559155e-17 -5.41712841e-17]
 [ 8.28828359e-17  9.98559155e-17  1.00000000e+00 -2.21053

# ↓以下試行錯誤していた際の残り

# 1列目に関するコード

In [ ]:
m = len(x)
n = len(XT)
a = XT[0][0:]
norm_a = np.linalg.norm(a)
d = np.sign(a[0]) * norm_a
w = - d * np.append([1], np.zeros(m-1-0))
u = (a - w) / (np.sqrt(norm_a*(norm_a + abs(a[0]))))

print(d)
print(u)
print(w)
print(a - np.dot(u, a) * u)

XT[0] = w
for i in range(1, n):
    XT[i] = XT[i] - np.dot(u, XT[i])*u

print(XT)

2.8284271247461903
[1.16342313 0.30389063 0.30389063 0.30389063 0.30389063 0.30389063
 0.30389063 0.30389063]
[-2.82842712 -0.         -0.         -0.         -0.         -0.
 -0.         -0.        ]
[-2.82842712e+00 -2.22044605e-16 -2.22044605e-16 -2.22044605e-16
 -2.22044605e-16 -2.22044605e-16 -2.22044605e-16 -2.22044605e-16]
[[-2.82842712e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00]
 [-7.07106781e+00 -8.46990313e-01 -8.46990313e-01  1.53009687e-01
   1.53009687e-01  1.15300969e+00  3.15300969e+00  4.15300969e+00]
 [-2.82842712e+01 -6.38796125e+00 -6.38796125e+00 -3.38796125e+00
  -3.38796125e+00  1.61203875e+00  1.76120387e+01  2.86120387e+01]
 [-1.36471609e+02 -3.46469130e+01 -3.46469130e+01 -2.76469130e+01
  -2.76469130e+01 -8.64691303e+00  8.93530870e+01  1.80353087e+02]]


# 2列目に関するコード

In [ ]:
a = XT[1][1:]
norm_a = np.linalg.norm(a)
d = np.sign(a[0]) * norm_a
w = - d * np.append([1], np.zeros(m-1-1))
u = (a - w) / (np.sqrt(norm_a*(norm_a + abs(a[0]))))

print(d)
print(u)
print(w)
print(a - np.dot(u, a) * u)

XT[1][1:] = w

for i in range(1+1, n):
    XT[i][1:] = XT[i][1:] - np.dot(u, XT[i][1:])*u

print(XT)

-5.477225575051661
[-1.0745411  -0.14391126  0.02599772  0.02599772  0.1959067   0.53572467
  0.70563366]
[5.47722558 0.         0.         0.         0.         0.
 0.        ]
[ 5.47722558e+00 -2.22044605e-16  5.55111512e-17  5.55111512e-17
  4.44089210e-16  8.88178420e-16  8.88178420e-16]
[[  -2.82842712   -0.           -0.           -0.           -0.
    -0.           -0.           -0.        ]
 [  -7.07106781    5.47722558    0.            0.            0.
     0.            0.            0.        ]
 [ -28.28427125   33.95879857   -0.98439576   -4.36412102   -4.36412102
    -5.74384627   -2.50329678    2.11697796]
 [-136.47160877  195.53695303   -3.81882175  -33.21604002  -33.21604002
   -50.6132583   -25.40769484   29.19508689]]


In [ ]:
a = np.array([[1,2,3,4]])

print(np.outer(a, a))


[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
A = np.array([[1,2],[3,4]])
c = np.array([1,1])
print(A@A)
print(A@c)

[[ 7 10]
 [15 22]]
[3 7]


In [ ]:
g = 0
for i in range(5):
    g += i**2
print(g)

30


In [ ]:
Q=H[:n][:m]
print(Q)
print(np.transpose(Q)@Q)
print(Q@np.transpose(Q))

[[-0.35355339 -0.35355339 -0.35355339 -0.35355339 -0.35355339 -0.35355339
  -0.35355339 -0.35355339]
 [-0.45643546 -0.27386128 -0.27386128 -0.09128709 -0.09128709  0.09128709
   0.45643546  0.63900965]
 [ 0.6044321   0.03296902  0.03296902 -0.31870056 -0.31870056 -0.45057666
  -0.05494837  0.47255601]
 [ 0.43910915 -0.26626005 -0.26626005 -0.17569541 -0.17569541  0.28230293
   0.58660014 -0.42410129]]
[[ 0.89148834  0.15301031  0.15301031 -0.10311564 -0.10311564 -0.06504786
   0.14103559 -0.0672654 ]
 [ 0.15301031  0.27198137  0.27198137  0.18627342  0.18627342  0.00997893
  -0.15799978  0.07850094]
 [ 0.15301031  0.27198137  0.27198137  0.18627342  0.18627342  0.00997893
  -0.15799978  0.07850094]
 [-0.10311564  0.18627342  0.18627342  0.26577226  0.26577226  0.21066637
  -0.00221754 -0.00942455]
 [-0.10311564  0.18627342  0.18627342  0.26577226  0.26577226  0.21066637
  -0.00221754 -0.00942455]
 [-0.06504786  0.00997893  0.00997893  0.21066637  0.21066637  0.4160476
   0.35702406 -0.

# 新しいコードの実装

In [ ]:
import numpy as np

#x = np.array([0, 1, 2, 3, 4, 5])
x = np.array([0, 1, 1, 2, 2, 3, 5, 6])
#y = np.array([10, 25, 51, 66, 97, 118])
y = np.array([1, 2, 3, 15, 15, 33,  75, 146])

m = len(x)

XT =np.array([np.ones(m), x, x**2, x**3])
n = len(XT)
print("m", m, "n", n)
print(XT)
print(np.dot(XT, np.transpose(XT)))

U = []
for i in range(n):
    a = XT[i][i:]
    norm_a = np.linalg.norm(a)
    d = np.sign(a[0]) * norm_a
    w = - d * np.append([1], np.zeros(m-1-i))
    u = (a - w) / (np.sqrt(norm_a*(norm_a + abs(a[0]))))
    U.append(np.append(np.zeros(i), u))

    XT[i][i:] = w

    for j in range(i+1, n):
        XT[j][i:] = XT[j][i:] - np.dot(u, XT[j][i:])*u

print(XT)

H = np.eye(m)
for i in range(n):
    H = np.array(np.eye(m) - np.outer(U[i], U[i])) @ H
y = H[:n] @ y
print("y", y)


X =  np.transpose(XT)
R = X[:n]
print(R)

alpha = np.zeros(n)

# Backward substitution
alpha[n-1] = y[n-1] / R[n-1][n-1]
for i in range(n-2, -1, -1): # n-2, n-1, ..., 0
    sum = 0
    for j in range(i+1,n): # i+1, i+2, ..., n-1
        sum += R[i][j]*alpha[j]
    alpha[i] = (y[i] - sum) / R[i][i]

print(alpha)
print("p(x) = {0:e} + {1:e} * x + {2:e} * x**2 + {3:e} * x**3".format(alpha[0], alpha[1], alpha[2], alpha[3]))

m 8 n 4
[[  1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.   1.   2.   2.   3.   5.   6.]
 [  0.   1.   1.   4.   4.   9.  25.  36.]
 [  0.   1.   1.   8.   8.  27. 125. 216.]]
[[8.000e+00 2.000e+01 8.000e+01 3.860e+02]
 [2.000e+01 8.000e+01 3.860e+02 2.036e+03]
 [8.000e+01 3.860e+02 2.036e+03 1.121e+04]
 [3.860e+02 2.036e+03 1.121e+04 6.314e+04]]
[[  -2.82842712   -0.           -0.           -0.           -0.
    -0.           -0.           -0.        ]
 [  -7.07106781    5.47722558    0.            0.            0.
     0.            0.            0.        ]
 [ -28.28427125   33.95879857    9.09945053    0.            0.
     0.            0.            0.        ]
 [-136.47160877  195.53695303   78.00471     -14.002329     -0.
    -0.           -0.           -0.        ]]
y [-102.53048327  125.97618823   41.21127959  -14.77083469]
[[  -2.82842712   -7.07106781  -28.28427125 -136.47160877]
 [  -0.            5.47722558   33.95879857  195.53695303]
 [  -0.            0.          

In [ ]:
import numpy as np

#x = np.array([0, 1, 2, 3, 4, 5])
x = np.array([0, 1, 1, 2, 2, 3, 5, 6])
#y = np.array([10, 25, 51, 66, 97, 118])
y = np.array([1, 2, 3, 15, 15, 33,  75, 146])

m = len(x)

XT =np.array([np.ones(m), x, x**2, x**3])
n = len(XT)
print("m", m, "n", n)
print(XT)
print(np.dot(XT, np.transpose(XT)))

U = []
for i in range(n):
    a = XT[i][i:]
    norm_a = np.linalg.norm(a)
    d = np.sign(a[0]) * norm_a
    w = - d * np.append([1], np.zeros(m-1-i))
    u = (a - w) / (np.sqrt(norm_a*(norm_a + abs(a[0]))))
    U.append(np.append(np.zeros(i), u))

    XT[i][i:] = w

    for j in range(i+1, n):
        XT[j][i:] = XT[j][i:] - np.dot(u, XT[j][i:])*u

print(XT)

#H = np.eye(m)
#for i in range(n):
#    H = np.array(np.eye(m) - np.outer(U[i], U[i])) @ H
#y = H[:n] @ y
#print("y", y)

#for i in reversed(range(n)):
for i in range(n):
    y = y - np.dot(U[i], y)*U[i]
print("y", y)

X =  np.transpose(XT)
R = X[:n]
print(R)

alpha = np.zeros(n)

# Backward substitution
alpha[n-1] = y[n-1] / R[n-1][n-1]
for i in range(n-2, -1, -1): # n-2, n-1, ..., 0
    sum = 0
    for j in range(i+1,n): # i+1, i+2, ..., n-1
        sum += R[i][j]*alpha[j]
    alpha[i] = (y[i] - sum) / R[i][i]

print(alpha)
print("p(x) = {0:e} + {1:e} * x + {2:e} * x**2 + {3:e} * x**3".format(alpha[0], alpha[1], alpha[2], alpha[3]))

m 8 n 4
[[  1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.   1.   2.   2.   3.   5.   6.]
 [  0.   1.   1.   4.   4.   9.  25.  36.]
 [  0.   1.   1.   8.   8.  27. 125. 216.]]
[[8.000e+00 2.000e+01 8.000e+01 3.860e+02]
 [2.000e+01 8.000e+01 3.860e+02 2.036e+03]
 [8.000e+01 3.860e+02 2.036e+03 1.121e+04]
 [3.860e+02 2.036e+03 1.121e+04 6.314e+04]]
[[  -2.82842712   -0.           -0.           -0.           -0.
    -0.           -0.           -0.        ]
 [  -7.07106781    5.47722558    0.            0.            0.
     0.            0.            0.        ]
 [ -28.28427125   33.95879857    9.09945053    0.            0.
     0.            0.            0.        ]
 [-136.47160877  195.53695303   78.00471     -14.002329     -0.
    -0.           -0.           -0.        ]]
y [-102.53048327  125.97618823   41.21127959  -14.77083469    1.27484207
    8.66309065  -10.31783092   -3.43815071]
[[  -2.82842712   -7.07106781  -28.28427125 -136.47160877]
 [  -0.            5.47722558   3

In [ ]:

X =  np.transpose(XT)
R = X[:n]
print(R)

alpha = np.zeros(n)

# Backward substitution
alpha[n-1] = y[n-1] / R[n-1][n-1]
for i in range(n-2, -1, -1): # n-2, n-1, ..., 0
    sum = 0
    for j in range(i+1,n): # i+1, i+2, ..., n-1
        sum += R[i][j]*alpha[j]
    alpha[i] = (y[i] - sum) / R[i][i]

print(alpha)
print("p(x) = {0:e} + {1:e} * x + {2:e} * x**2 + {3:e} * x**3".format(alpha[0], alpha[1], alpha[2], alpha[3]))

In [ ]:
print(U)

[array([1.16342313, 0.30389063, 0.30389063, 0.30389063, 0.30389063,
       0.30389063, 0.30389063, 0.30389063]), array([ 0.        , -1.0745411 , -0.14391126,  0.02599772,  0.02599772,
        0.1959067 ,  0.53572467,  0.70563366]), array([ 0.        ,  0.        , -1.05270219, -0.455592  , -0.455592  ,
       -0.59962829, -0.26133143,  0.22100172]), array([ 0.        ,  0.        ,  0.        ,  1.07555497,  0.14580239,
       -0.26598886, -0.33831718,  0.79794397])]


# 更なる改良


In [ ]:
import numpy as np

#x = np.array([0, 1, 2, 3, 4, 5])
x = np.array([0, 1, 1, 2, 2, 3, 5, 6])
#y = np.array([10, 25, 51, 66, 97, 118])
y = np.array([1, 2, 3, 15, 15, 33,  75, 146])

m = len(x)

XT =np.array([np.ones(m), x, x**2, x**3])
n = len(XT)
print("m", m, "n", n)
print(XT)
print(np.dot(XT, np.transpose(XT)))

U = []
for i in range(n):
    a = XT[i][i:]
    norm_a = np.linalg.norm(a)
    d = np.sign(a[0]) * norm_a
    w = - d * np.append([1], np.zeros(m-1-i))
    u = (a - w) / (np.sqrt(norm_a*(norm_a + abs(a[0]))))
    print("u=", u)
    U.append(np.append(np.zeros(i), u))

    XT[i][i:] = w

    for j in range(i+1, n):
        XT[j][i:] = XT[j][i:] - np.dot(u, XT[j][i:])*u
    y = y - np.dot(u, y[i:]) * np.append(np.zeros(i), u)
    print("y=", y)

print(XT)

#H = np.eye(m)
#for i in range(n):
#    H = np.array(np.eye(m) - np.outer(U[i], U[i])) @ H
#y = H[:n] @ y
#print("y", y)

#for i in reversed(range(n)):
#for i in range(n):
#    y = y - np.dot(U[i], y)*U[i]
#print("y", y)

X =  np.transpose(XT)
R = X[:n]
print(R)

alpha = np.zeros(n)

# Backward substitution
alpha[n-1] = y[n-1] / R[n-1][n-1]
for i in range(n-2, -1, -1): # n-2, n-1, ..., 0
    sum = 0
    for j in range(i+1,n): # i+1, i+2, ..., n-1
        sum += R[i][j]*alpha[j]
    alpha[i] = (y[i] - sum) / R[i][i]

print(alpha)
print("p(x) = {0:e} + {1:e} * x + {2:e} * x**2 + {3:e} * x**3".format(alpha[0], alpha[1], alpha[2], alpha[3]))

m 8 n 4
[[  1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.   1.   2.   2.   3.   5.   6.]
 [  0.   1.   1.   4.   4.   9.  25.  36.]
 [  0.   1.   1.   8.   8.  27. 125. 216.]]
[[8.000e+00 2.000e+01 8.000e+01 3.860e+02]
 [2.000e+01 8.000e+01 3.860e+02 2.036e+03]
 [8.000e+01 3.860e+02 2.036e+03 1.121e+04]
 [3.860e+02 2.036e+03 1.121e+04 6.314e+04]]
u= [1.16342313 0.30389063 0.30389063 0.30389063 0.30389063 0.30389063
 0.30389063 0.30389063]
y= [-102.53048327  -25.04256341  -24.04256341  -12.04256341  -12.04256341
    5.95743659   47.95743659  118.95743659]
u= [-1.0745411  -0.14391126  0.02599772  0.02599772  0.1959067   0.53572467
  0.70563366]
y= [-102.53048327  125.97618823   -3.81690667  -15.69634949  -15.69634949
  -21.5757923   -27.33467793   19.78587926]
u= [-1.05270219 -0.455592   -0.455592   -0.59962829 -0.26133143  0.22100172]
y= [-102.53048327  125.97618823   41.21127959    3.79110086    3.79110086
    4.07265297  -16.15651134   10.33277225]
u= [ 1.07555497  0.14580239 -0.